absolute_urls: false

home:
  alias: '/blog'

pages:
  theme: notepad
  markdown_extra: true
  process:
    markdown: true
    twig: false
  markdown:
    extra: true

cache:
  enabled: false
  gzip: true
  lifetime: 604800
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: false
  css_rewrite: true
  js_pipeline: true
  js_minify: false

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
